MyApp\Component\Product\Domain\Owner:
    type: entity
    repositoryClass: MyApp\Bundle\ProductBundle\Owner\Repository\OwnerRepository
    table: owner
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
    lifecycleCallbacks: {  }
