MyApp\Component\Product\Domain\Product:
    type: entity
    repositoryClass: MyApp\Bundle\ProductBundle\Product\Repository\ProductRepository
    table: product
    indexes:
        IDX_D34A04AD7E3C61F9:
            columns:
                - owner_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        description:
            type: text
            nullable: false
            length: null
            options:
                fixed: false
        name:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        price:
            type: decimal
            nullable: false
            precision: 10
            scale: 2
    manyToOne:
        owner:
            targetEntity: Owner
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                owner_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
